#!/usr/bin/perl

open (FILE, @ARGV[0]) or die "Cannot open file: $!";
push(@outLines, "#NEXUS\nbegin trees;\n");

$num=1;
while($line = <FILE> ) {
	if($num==1 && substr($line, 0, 1) eq "#"){
		print("File appears to already be NEXUS!\n");
		exit;	
	}
	push(@outLines, "tree tree$num = [&U]");
	push(@outLines, $line);
	$num=$num + 1;
}

push(@outLines, "end;");
open (OUTFILE, ">@ARGV[0]");
print (OUTFILE @outLines);
close(OUTFILE);

