#!/usr/bin/env python
import sys

#iterate backwards over all of the history lines passed on stdin
#only storing the most recent of each command
line_dict = {}
for line in [ line.split(None, 1) for line in sys.stdin ][::-1]:
    if line[1] not in line_dict:
        line_dict[line[1]] = line[0]

#write back out after sorting by number
sys.stdout.write(''.join( ( str(line[0]) + '\t' + line[1] for line in sorted( [ (int(num), command) for command, num in line_dict.iteritems() ] ) ) ))
