#!/usr/bin/env python3
import sys
import re

#iterate backwards over all of the history lines passed on stdin
#only storing the most recent of each command
line_dict = {}
for line in [ l for l in sys.stdin ][::-1]:
    #some history numbers have an asterisk after them.  Don't know why.
    line = line.split(None, 1)
    line[0] = re.sub('[*]$', '', line[0])
    if len(line) > 1 and line[1] not in line_dict:
        line_dict[line[1]] = line[0]

#write back out after sorting by number
sys.stdout.write(''.join( ( str(line[0]) + '\t' + line[1] for line in sorted( [ (int(num), command) for command, num in line_dict.items() ] ) ) ))
